# Generated by nixos-generate-config. Keep host hardware changes in this file.
{
  config,
  lib,
  modulesPath,
  ...
}:
{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot = {
    extraModulePackages = [ ];
    initrd = {
      availableKernelModules = [
        "ahci"
        "nvme"
        "sd_mod"
        "thunderbolt"
        "usb_storage"
        "usbhid"
        "xhci_pci"
      ];
      kernelModules = [ ];
    };
    kernelModules = [ "kvm-amd" ];
    kernelParams = [ "kvm.enable_virt_at_load=0" ];
  };

  fileSystems = {
    "/" = {
      device = "/dev/disk/by-uuid/6a57da19-d096-462d-ad59-345ee3c32231";
      fsType = "ext4";
    };
    "/boot" = {
      device = "/dev/disk/by-uuid/ADC3-9173";
      fsType = "vfat";
      options = [
        "dmask=0077"
        "fmask=0077"
      ];
    };
  };

  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  networking.useDHCP = lib.mkDefault true;
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  swapDevices = [ { device = "/dev/disk/by-uuid/9077566b-906d-4d22-89e4-585f7ec6694f"; } ];
}
